server:
  port: 8099
spring:
  application:
    name: gateway-server
    # 配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 2a57e550-6295-4269-b1b4-268c46021020
    gateway:
      discovery:
        locator:
          enabled: true
      # 是否开启网关
      enabled: true
      routes:
      - id: user_route    #路由ID，全局唯一
        uri: http://127.0.0.1:8010  #目标微服务的请求地址和端口
        predicates:
        - Before=2021-08-11T14:31:16.378+08:00[Asia/Shanghai]
        - Method=post
